# The URL the site will be built for
base_url = "http://localhost:1111"
title = "Hakuna Matata Project"
description = "A Zola project for the Hakuna site."
theme = "hakuna_theme"
# Whether to automatically compile all Sass files in the sass directory
compile_sass = true

# Whether to build a search index to be used later on by a JavaScript library
build_search_index = false

[markdown]
# Whether to do syntax highlighting
# Theme can be customised by setting the `highlight_theme` variable to a theme supported by Zola
highlight_code = false

[extra]
# Put all your custom variables here



nav = [
    { name = "Home", link = "/" },
    { name = "Docs", link = "/docs/" },
    { name = "Blog", link = "/blog/" }
]


[extra.author]

avatar = "images/imageee.png"


